@ProyectTest_HostAddress = http://localhost:5217

### Intentar crear una tarea con título vacío (debe fallar con 400)
POST {{ProyectTest_HostAddress}}/api/tareas
Content-Type: application/json

{
  "titulo": "",
  "completada": false
}

### Intentar crear con título muy corto (debe fallar con 400)
POST {{ProyectTest_HostAddress}}/api/tareas
Content-Type: application/json

{
  "titulo": "Fundamentos de Programacion",
  "completada": false
}

### Crear una válida (debe dar 201)
POST {{ProyectTest_HostAddress}}/api/tareas
Content-Type: application/json

{
  "titulo": "Esta tarea sí es válida",
  "completada": false
}